### ISSUE TITLE
I love the extension! I would love it even more if you would consider implementing two features/options...

### ISSUE THREAD

**Issue by DRschulman** [mlava/yesterday-tomorrow#1]
Hi Mark - love the extension. I would love it if you would consider implementing two features/options:

1. Have the Today button go to the current DNP the same way that Alt-D does, so that the "VIEW MORE" option appears below the current DNP listing. 
2. An option to allow the Yesterday and Today buttons to become previous/next day buttons, instead of just the day before or after the current date.

Thanks for listening!

**Comment by mlava** [comment]
@DRschulman 
Thanks for the feedback.
re 1. I hadn't thought it all that useful to return to the log page using the home button, but can implement a switch in settings to do so
re 2. I can make a switch to make yesterday/tomorrow buttons always more back/forward one day, or always go to yesterday/tomorrow.
Will update and let you know. Might be a week or so, as I'm under the pump and then travelling...

**Comment by DRschulman** [comment]
Fabulous! Thank you!

- David Schulman
c: 703.405.9954

**Comment by mlava** [comment]
#2 is now implemented and waiting for approval in roam depot github. I forgot about the log pages one so will get that done soon

**Comment by DRschulman** [comment]
Awesome, thanks!

- David Schulman

**Comment by mlava** [comment]
log pages is now also in this https://github.com/Roam-Research/roam-depot/pull/248 update
Cheers!

**Comment by DRschulman** [comment]
How long does it take RR to get this through their review process?

- David Schulman
c: 703.405.9954

**Comment by mlava** [comment]
There's no fixed time, I'm afraid. I don't know how much they got done since last post, but it's often Thursday/Friday when they are doing it.

**Comment by DRschulman** [comment]
Ok, thanks.

- David Schulman
c: 703.405.9954

**Comment by DRschulman** [comment]
It's live and works like a champ! Thank you!!!

- David Schulman

**Comment by mlava** [comment]
Great!
Glad it's working as intended.

**Comment by DRschulman** [comment]
Oops - I spoke too soon. I just noticed a bug. Please see this screencast
<https://www.screencast.com/t/GL0WkrnHmVeq>

Thanks,

- David Schulman
c: 703.405.9954

**Comment by DRschulman** [comment]
Hi Mark,

Just confirming you've received this about the bug.

- David Schulman
c: 703.405.9954

**Comment by mlava** [comment]
Thanks David. I've just pushed a fix...

**Comment by DRschulman** [comment]
Thanks! I've updated and refreshed - but still having the issue. Maybe it
takes a day or two for the push to make it into an update?

- David Schulman
c: 703.405.9954

**Comment by mlava** [comment]
Yeah, sorry it has to be approved by the RR guys first.
This is the PR - https://github.com/Roam-Research/roam-depot/pull/274
When it is approved and merged you'll be able to update on your end.
Mark

**Comment by DRschulman** [comment]
Thank you so much.

- David Schulman
c: 703.405.9954
